//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElektronikSatisi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EmarketEntities23 : DbContext
    {
        public EmarketEntities23()
            : base("name=EmarketEntities23")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminLogin> AdminLogin { get; set; }
        public virtual DbSet<Kuponlar> Kuponlar { get; set; }
        public virtual DbSet<Manset> Manset { get; set; }
        public virtual DbSet<MesajBox> MesajBox { get; set; }
        public virtual DbSet<Resimler> Resimler { get; set; }
        public virtual DbSet<SatinAlinan> SatinAlinan { get; set; }
        public virtual DbSet<Sepet> Sepet { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Urunler> Urunler { get; set; }
        public virtual DbSet<UserKupon> UserKupon { get; set; }
        public virtual DbSet<UserLogin> UserLogin { get; set; }
        public virtual DbSet<Yorumlar> Yorumlar { get; set; }
    }
}
