//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElektronikSatisi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kuponlar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kuponlar()
        {
            this.UserKupon = new HashSet<UserKupon>();
        }
    
        public int id { get; set; }
        public string Kisim { get; set; }
        public Nullable<int> Kindirim { get; set; }
        public Nullable<int> Ktutarlimit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserKupon> UserKupon { get; set; }
    }
}
