//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElektronikSatisi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MesajBox
    {
        public int id { get; set; }
        public string MBUrun { get; set; }
        public string MBIsim { get; set; }
        public string MBSoyisim { get; set; }
        public string MBMail { get; set; }
        public string MBMesaj { get; set; }
        public string MBTelefon { get; set; }
    }
}
