//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElektronikSatisi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SatinAlinan
    {
        public int id { get; set; }
        public string SAUrun { get; set; }
        public string SAIsim { get; set; }
        public string SASoyisim { get; set; }
        public string SAMail { get; set; }
        public string SAAdres { get; set; }
        public string SATelefon { get; set; }
        public string SAMesaj { get; set; }
    }
}
