//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElektronikSatisi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sepet
    {
        public int id { get; set; }
        public string SBaslik { get; set; }
        public string SAciklama { get; set; }
        public string SResiyomYol { get; set; }
        public string SFiyat { get; set; }
        public string SKategori { get; set; }
        public Nullable<int> SAdet { get; set; }
        public Nullable<int> SSepetUser { get; set; }
        public Nullable<int> SSepetUrun { get; set; }
        public Nullable<int> SUadet { get; set; }
    
        public virtual Urunler Urunler { get; set; }
        public virtual UserLogin UserLogin { get; set; }
    }
}
