//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElektronikSatisi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yorumlar
    {
        public int id { get; set; }
        public string YYorum { get; set; }
        public string YIsim { get; set; }
        public string YSoyisim { get; set; }
        public string YResimYolu { get; set; }
        public Nullable<int> YYildiz { get; set; }
        public Nullable<int> YYorumUrun { get; set; }
        public Nullable<int> YYorumUser { get; set; }
    
        public virtual Urunler Urunler { get; set; }
        public virtual UserLogin UserLogin { get; set; }
    }
}
